set_project("sigma_rt")
set_version("0.2.1")
set_languages("c23")
set_toolchains("clang")
set_toolset("ld", "clang")
add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "."})

package("sigma_sys")
    set_homepage("https://github.com/0xveya/sigma_libft")
    set_description("Sigma's typed Linux syscall boundary")
    add_urls("https://github.com/0xveya/sigma_libft.git")
    on_install(function (package)
        import("package.tools.xmake").install(package,
            {sigma_sys_only = true}, {target = "sigma_sys"})
    end)
package_end()

package("sigma_malloc")
    set_homepage("https://github.com/0xveya/sigma-malloc")
    set_description("Sigma's composable C23 allocator")
    add_urls("https://github.com/0xveya/sigma-malloc.git")
    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)
package_end()

package("sigma_libft")
    set_homepage("https://github.com/0xveya/sigma_libft")
    set_description("Sigma's C23 foundation library")
    add_urls("https://github.com/0xveya/sigma_libft.git")
    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)
package_end()

add_requires("sigma_sys v0.2.2", {system = false})
add_requires("sigma_malloc v0.2.3", {system = false})
add_requires("sigma_libft v0.2.2", {system = false})

local warnings = {"all", "extra", "pedantic"}

local function configure(target_name)
    target(target_name)
        set_warnings(table.unpack(warnings))
        add_cflags("-fblocks", "-ffreestanding", "-fno-builtin", "-fno-stack-protector", "-Wshadow", "-Wconversion", "-Wdouble-promotion", "-Wformat=2", "-Wundef", {force = true})
        add_includedirs("include")
        add_packages("sigma_libft", "sigma_malloc", "sigma_sys", {public = true})
end

configure("sigma_rt")
    set_kind("static")
    add_headerfiles("include/(**.h)")
    add_files("src/*.c")

configure("sigma-rt-app")
    set_kind("binary")
    add_deps("sigma_rt")
    add_files("main.c", "src/start/x86_64_linux.S")
    add_ldflags("-nostdlib", "-static", "-no-pie", "-Wl,-e,_start", {force = true})

configure("sigma-rt-app-libc")
    set_kind("binary")
    set_default(false)
    add_deps("sigma_rt")
    add_files("main.c", "src/start/x86_64_linux_libc.S")
    add_ldflags("-nostartfiles", "-Wl,-e,_start", {force = true})

configure("map-tests")
    set_kind("binary")
    set_default(false)
    add_files("tests/map.c")
    add_tests("map")

configure("env-tests")
    set_kind("binary")
    set_default(false)
    add_files("tests/env.c", "src/args.c", "src/env.c", "src/rt.c")
    add_tests("environment", {runenvs = {HOME = "/tmp", USER = "veya", EMPTY = "", THING = "a=b=c"}, trim_output = true, pass_outputs = "HOME = /tmp"})
