name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v6

      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> "$FORGEJO_PATH"

      - name: Install toolchain
        run: mise install

      - name: Show versions
        run: |
          mise exec -- zig version
          mise exec -- clang-format --version
          mise exec -- cppcheck --version

      - name: Format
        run: |
          mise exec -- clang-format --dry-run --Werror \
            main.c \
            $(find src include tests \
              -type f \( -name '*.c' -o -name '*.h' \))

      - name: Lint
        run: mise run check

      - name: Test
        run: mise run test
